# Generated by Django 5.2.8 on 2025-11-15 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empl_veterinario', '0001_initial'),
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('PK_IdCita', models.IntegerField(db_column='PK_IdCita', primary_key=True, serialize=False)),
                ('Fecha', models.DateField(db_column='Fecha')),
                ('Hora', models.TimeField(db_column='Hora')),
                ('Motivo', models.CharField(db_column='Motivo', max_length=200)),
                ('Estado', models.CharField(db_column='Estado', max_length=50)),
                ('FK_IdMascota', models.ForeignKey(db_column='FK_IdMascota', on_delete=django.db.models.deletion.CASCADE, to='mascota.mascota')),
                ('FK_IdVeterinario', models.ForeignKey(db_column='FK_IdVeterinario', on_delete=django.db.models.deletion.CASCADE, to='empl_veterinario.veterinario')),
            ],
            options={
                'db_table': 'Cita',
            },
        ),
    ]
