# Generated by Django 5.2.8 on 2025-11-19 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empl_veterinario', '0001_initial'),
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.BigAutoField(db_column='id_cita', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='fecha')),
                ('hora', models.TimeField(db_column='hora')),
                ('motivo', models.CharField(db_column='motivo', max_length=200)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Programada', 'Programada'), ('Atendida', 'Atendida'), ('Cancelada', 'Cancelada')], db_column='estado', max_length=50)),
                ('mascota_id', models.ForeignKey(db_column='mascota_id', on_delete=django.db.models.deletion.CASCADE, to='mascota.mascota')),
                ('veterinario_id', models.ForeignKey(db_column='veterinario_id', on_delete=django.db.models.deletion.CASCADE, to='empl_veterinario.veterinario')),
            ],
            options={
                'db_table': 'cita',
            },
        ),
    ]
