# Generated by Django 5.2.8 on 2025-11-15 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('PK_IdAdministrador', models.OneToOneField(db_column='PK_IdAdministrador', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='empleado.empleado')),
                ('Licencia', models.CharField(db_column='Licencia', max_length=50)),
            ],
            options={
                'db_table': 'Administrador',
            },
        ),
    ]
