# Generated by Django 5.2.8 on 2025-11-19 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('user', models.OneToOneField(db_column='id_administrador', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Telefono', models.CharField(db_column='telefono', max_length=20)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
    ]
