# Generated by Django 5.2.8 on 2025-11-19 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='Licencia',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='PK_IdAdministrador',
        ),
        migrations.AddField(
            model_name='administrador',
            name='Telefono',
            field=models.CharField(db_column='Telefono', default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='user',
            field=models.OneToOneField(db_column='PK_IdAdministrador', default='0000000000', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='administrador',
            table=None,
        ),
    ]
