# Generated by Django 5.2.8 on 2025-11-19 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamiento', models.BigAutoField(db_column='id_tratamiento', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=200)),
                ('medicamento', models.CharField(db_column='medicamento', max_length=100)),
                ('dosis', models.CharField(db_column='dosis', max_length=50)),
                ('duracion', models.CharField(db_column='duracion', max_length=50)),
                ('fecha_inicio', models.DateField(db_column='fecha_inicio')),
                ('cita_id', models.ForeignKey(db_column='cita_id', on_delete=django.db.models.deletion.CASCADE, to='cita.cita')),
            ],
            options={
                'db_table': 'tratamiento',
            },
        ),
    ]
