# Generated by Django 5.2.8 on 2025-11-15 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('PK_IdTratamiento', models.IntegerField(db_column='PK_IdTratamiento', primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(db_column='Descripcion', max_length=200)),
                ('Medicamento', models.CharField(db_column='Medicamento', max_length=100)),
                ('Dosis', models.CharField(db_column='Dosis', max_length=50)),
                ('Duracion', models.CharField(db_column='Duracion', max_length=50)),
                ('Fecha_Inicio', models.DateField(db_column='Fecha_Inicio')),
                ('FK_IdCita', models.ForeignKey(db_column='FK_IdCita', on_delete=django.db.models.deletion.CASCADE, to='cita.cita')),
            ],
            options={
                'db_table': 'Tratamiento',
            },
        ),
    ]
