# Generated by Django 5.2.8 on 2025-11-20 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagRegister', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='pagregister_cliente',
        ),
        migrations.AlterModelTable(
            name='mascota',
            table='pagregister_mascota',
        ),
    ]
