# Generated by Django 5.2.8 on 2025-11-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(db_column='id_cliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('apellido', models.CharField(db_column='apellido', max_length=50)),
                ('telefono', models.CharField(db_column='telefono', max_length=20)),
                ('direccion', models.CharField(db_column='direccion', max_length=150)),
                ('email', models.CharField(db_column='email', max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_column='estado', max_length=20)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
