# Generated by Django 5.2.8 on 2025-11-15 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
        ('cita', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('PK_IdFactura', models.IntegerField(db_column='PK_IdFactura', primary_key=True, serialize=False)),
                ('Fecha_Emision', models.DateField(db_column='Fecha_Emision')),
                ('Monto_Total', models.DecimalField(db_column='Monto_Total', decimal_places=2, max_digits=10)),
                ('Estado_Pago', models.CharField(db_column='Estado_Pago', max_length=50)),
                ('FK_IdAdministrador', models.ForeignKey(db_column='FK_IdAdministrador', on_delete=django.db.models.deletion.CASCADE, to='administrador.administrador')),
                ('FK_IdCita', models.ForeignKey(db_column='FK_IdCita', on_delete=django.db.models.deletion.CASCADE, to='cita.cita')),
                ('FK_IdCliente', models.ForeignKey(db_column='FK_IdCliente', on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'db_table': 'Factura',
            },
        ),
    ]
