# Generated by Django 5.2.8 on 2025-11-19 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
        ('cita', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.BigAutoField(db_column='id_factura', primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(db_column='fecha_emision')),
                ('monto_total', models.DecimalField(db_column='monto_total', decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(db_column='estado_pago', max_length=50)),
                ('administrador_id', models.ForeignKey(db_column='administrador_id', on_delete=django.db.models.deletion.CASCADE, to='administrador.administrador')),
                ('cita_id', models.ForeignKey(db_column='cita_id', on_delete=django.db.models.deletion.CASCADE, to='cita.cita')),
                ('cliente_id', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'db_table': 'factura',
            },
        ),
    ]
