# Generated by Django 5.2.8 on 2025-11-15 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('PK_IdMascota', models.IntegerField(db_column='PK_IdMascota', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('Especie', models.CharField(db_column='Especie', max_length=50)),
                ('Raza', models.CharField(db_column='Raza', max_length=50)),
                ('Edad', models.IntegerField(db_column='Edad')),
                ('Peso', models.DecimalField(db_column='Peso', decimal_places=2, max_digits=5)),
                ('FK_IdCliente', models.ForeignKey(db_column='FK_IdCliente', on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'db_table': 'Mascota',
            },
        ),
    ]
