# Generated by Django 5.2.8 on 2025-11-19 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.BigAutoField(db_column='id_mascota', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('especie', models.CharField(db_column='especie', max_length=50)),
                ('raza', models.CharField(db_column='raza', max_length=50)),
                ('edad', models.IntegerField(db_column='edad')),
                ('peso', models.DecimalField(db_column='peso', decimal_places=2, max_digits=5)),
                ('cliente_id', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'db_table': 'mascota',
            },
        ),
    ]
