# Generated by Django 5.2.8 on 2025-11-15 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('PK_IdVeterinario', models.OneToOneField(db_column='PK_IdVeterinario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='empleado.empleado')),
                ('Especialidad', models.CharField(db_column='Especialidad', max_length=100)),
                ('Licencia', models.CharField(db_column='Licencia', max_length=50)),
            ],
            options={
                'db_table': 'Veterinario',
            },
        ),
    ]
