# Generated by Django 5.2.8 on 2025-11-19 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id_veterinario', models.OneToOneField(db_column='id_veterinario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='empleado.empleado')),
                ('especialidad', models.CharField(db_column='especialidad', max_length=100)),
            ],
            options={
                'db_table': 'veterinario',
            },
        ),
    ]
