# Generated by Django 5.2.8 on 2025-11-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('PK_IdEmpleado', models.IntegerField(db_column='PK_IdEmpleado', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('Apellido', models.CharField(db_column='Apellido', max_length=50)),
                ('Telefono', models.CharField(db_column='Telefono', max_length=20)),
            ],
            options={
                'db_table': 'Empleado',
            },
        ),
    ]
