# Generated by Django 5.2.8 on 2025-11-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.BigAutoField(db_column='id_empleado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('apellido', models.CharField(db_column='apellido', max_length=50)),
                ('telefono', models.CharField(db_column='telefono', max_length=20)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
    ]
