# Generated by Django 5.2.8 on 2025-11-15 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_de_Vacunas',
            fields=[
                ('PK_IdVacuna', models.IntegerField(db_column='PK_IdVacuna', primary_key=True, serialize=False)),
                ('Nombre_Vacuna', models.CharField(db_column='Nombre_Vacuna', max_length=100)),
                ('Fecha_Aplic', models.DateField(db_column='Fecha_Aplic')),
                ('Fecha_Venc', models.DateField(db_column='Fecha_Venc')),
                ('Lote', models.CharField(db_column='Lote', max_length=50)),
                ('FK_IdMascota', models.ForeignKey(db_column='FK_IdMascota', on_delete=django.db.models.deletion.CASCADE, to='mascota.mascota')),
            ],
            options={
                'db_table': 'Historial_de_Vacunas',
            },
        ),
    ]
