# Generated by Django 5.2.8 on 2025-11-19 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_de_Vacunas',
            fields=[
                ('id_vacuna', models.BigAutoField(db_column='id_vacuna', primary_key=True, serialize=False)),
                ('nombre_vacuna', models.CharField(db_column='nombre_vacuna', max_length=100)),
                ('fecha_aplic', models.DateField(db_column='fecha_aplic')),
                ('fecha_venc', models.DateField(db_column='fecha_venc')),
                ('lote', models.CharField(db_column='lote', max_length=50)),
                ('mascota_id', models.ForeignKey(db_column='mascota_id', on_delete=django.db.models.deletion.CASCADE, to='mascota.mascota')),
            ],
            options={
                'db_table': 'historial_de_Vacunas',
            },
        ),
    ]
